code --install-extension charliermarsh.ruff --force
code --install-extension cschlosser.doxdocgen --force
code --install-extension davidanson.vscode-markdownlint --force
code --install-extension emmanuelbeziat.vscode-great-icons --force
code --install-extension esbenp.prettier-vscode --force
code --install-extension github.copilot-chat --force
code --install-extension james-yu.latex-workshop --force
code --install-extension mechatroner.rainbow-csv --force
code --install-extension ms-python.debugpy --force
code --install-extension ms-python.isort --force
code --install-extension ms-python.python --force
code --install-extension ms-python.vscode-pylance --force
code --install-extension ms-python.vscode-python-envs --force
code --install-extension ms-toolsai.datawrangler --force
code --install-extension ms-toolsai.jupyter --force
code --install-extension ms-toolsai.jupyter-keymap --force
code --install-extension ms-toolsai.jupyter-renderers --force
code --install-extension ms-toolsai.vscode-jupyter-cell-tags --force
code --install-extension ms-toolsai.vscode-jupyter-slideshow --force
code --install-extension ms-vscode.cmake-tools --force
code --install-extension ms-vscode.cpp-devtools --force
code --install-extension ms-vscode.cpptools --force
code --install-extension ms-vscode.cpptools-extension-pack --force
code --install-extension ms-vscode.cpptools-themes --force
code --install-extension ms-vscode.powershell --force
code --install-extension ms-vscode-remote.vscode-remote-extensionpack --force
code --install-extension oderwat.indent-rainbow --force
code --install-extension redhat.vscode-yaml --force
code --install-extension rust-lang.rust-analyzer --force
code --install-extension streetsidesoftware.code-spell-checker --force
code --install-extension usernamehw.errorlens --force
