[project]
name = "scicomp101"
version = "0.1.0"
description = "Foundations of Scientific Computing (scicomp101)"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "apptools",
    "beautifulsoup4",
    "black",
    "configobj",
    "datasets",
	"envisage",	
    "ipympl",
    "ipython",
    "jax[cpu]",
    "joblib",
    "jupyter",
    "matplotlib",
    "networkx",
    "numba",
    "numexpr",
    "numpy",
    "pandas",
    "pip",
    "pulp",
	"puremagic",
    "pyface",
    "pygame-ce",
    "pyqt6",
    "pyside6",
    "pyside6-addons",
    "ruff",
    "scikit-learn",
    "scipy",
    "seaborn",
    "selenium",
    "setuptools",
    "sympy",
    "tqdm",
    "traitsui",
    "transformers",
    "webdriver-manager",
    "wheel",
    "highspy",
    "pyvista[all]",
]


[tool.uv.workspace]
members = [
    "scicomp101",
]

[tool.ruff]
lint.extend-select = ["I", "C4", "ISC", "SIM", "TCH"]
lint.ignore = []
show-fixes = true
target-version = "py314"

