#!/usr/bin/env -S uv run
"""
Count integers whose binary representation contains exactly two adjacent 1 bits.

This script focuses on a specific and simple class of bit patterns:
numbers whose binary form is '11' followed only by zeros, such as:

    3   ->  0b11
    6   ->  0b110
    12  ->  0b1100
    24  ->  0b11000

These values are generated by left-shifting the binary pattern '11',
which is equivalent to multiplying 3 by successive powers of two.
"""


def count_integers_with_two_adjacent_one_bits(min_n: int, max_n: int) -> int:
    """
    Count integers in [min_n, max_n] whose binary representation is '11' followed by zeros.

    The function generates integers with exactly two adjacent 1 bits and no
    additional 1s elsewhere. Each value is produced by left-shifting the
    binary pattern '11', corresponding to multiplying by powers of two.

    Parameters
    ----------
    min_n : int
        Inclusive lower bound of the range.
    max_n : int
        Inclusive upper bound of the range.

    Returns
    -------
    int
        The number of integers in the range whose binary form contains
        exactly two adjacent 1 bits.
    """
    n = 3  # Binary: 0b11 (two adjacent 1 bits)
    count = 0

    # Repeatedly left-shift '11' until we exceed the upper bound
    while n <= max_n:
        if n >= min_n:
            count += 1
        n *= 2  # Left shift by one bit

    return count


def main() -> None:
    """Run example ranges and display results."""
    for lo, hi in [(1, 192), (10**25, 10**45)]:
        count = count_integers_with_two_adjacent_one_bits(lo, hi)
        print(
            "Count of integers with two adjacent 1 bits between "
            f"{lo} and {hi} = {count}"
        )


if __name__ == "__main__":
    main()
